version: 2
    
updates:
  - package-ecosystem: "cargo"
    labels:
      - "automerge"
    directories:
      - "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        update-types: [ patch, minor ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
            - "*"
